import { Rubik } from 'next/font/google'
import type { Metadata } from "next"
import "./globals.css"
import { Toaster } from '@/components/ui/toaster';
import {Footer} from "@/components/ui/Footer";


const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rubik"
})

export const metadata: Metadata = {
  title: "Z",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
      <link rel="icon" href="./logo.png" type="image/x-icon"/>
      </head>
      <body
        className={`${rubik.variable} antialiased relative`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
